apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: projeto-grupo4-app
          image: node:20.9.0-alpine3.18
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          #livenessProbe:
            #httpGet:
              #path: /healthcheck
              #port: 8080
            #initialDelaySeconds: 15
            #periodSeconds: 20
          #readinessProbe:
            #httpGet:
              #path: /readycheck
              #port: 8080
            #initialDelaySeconds: 10
            #periodSeconds: 15