version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - app:/usr/src/app
    restart: always
  
  postgresql-master:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - postgresql_master_data:/bitnami/postgresql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=NONE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=development_database
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-slave:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5434:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes  
volumes:
  postgresql_master_data:
  app:
    driver: local




    #1-Guardar este arquivo aqui C:\Program Files\PostgreSQL\16\data
    #2-Linha de comandos como adiministrador
    #3-cd C:\Program Files\PostgreSQL\16\data
    #4-docker-compose up 
    #5-docker pull bitnami/postgresql (não me lembro se é necessário)
    #Abrir pgAdmin4 
    #Register server>Master>localhost>5433>postgres>save
