apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
spec:
  selector:
    app: postgres-master
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave-service
spec:
  selector:
    app: postgres-slave
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080